version: "3.9"

services:
  golang:
    build:
      context: ./golang
      dockerfile: Dockerfile
    volumes:
      - ./golang/app:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    # command: go run main.go
    tty: true
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - ENV=dev
    depends_on:
      - db

  db:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app
    ports:
      - "3366:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-init:/docker-entrypoint-initdb.d

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    volumes:
      - ./python:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - redis
  redis:
    image: "redis:alpine"

volumes:
  mysql-data:
  mysql-init:
