name: build and push

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "TAG=build-push-action-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - name: Set up Docker Buildx # cache 使うには必要っぽい https://github.com/fchimpan/servers/actions/runs/6784317277/job/18440371258?pr=20
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Image build and push
        uses: docker/build-push-action@v5
        with:
          context: ./golang/app
          push: true
          tags: r4mimu/build-push-action-dev:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "TAG=build-push-command-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: docker build
        run: docker build -t r4mimu/build-push-command-dev:${{ env.TAG }} ./golang/app
      - name: docker push
        run: docker push r4mimu/build-push-command-dev:${{ env.TAG }}
